import { mat4 } from 'gl-matrix';
import { NODE_TYPES } from '../nodeTypes';
import { VideoEntity, World } from '../..';

export const worldDefaults: World = {
  skybox: {
    key: '',
    'key-env': '',
    show: true,
  },
  color: [0, 0, 0],
  transparent: false,
  skyboxRotation: [0, 0, 0],
  skyboxEnvRotation: [0, 0, 0],
  shadow: {
    level: 0,
    enabled: false,
    position: [0, 0, 0],
    fov: false,
    texture: [1024, 1024],
    volume: [50, 50, 50],
    center: [0, 0, 0],
    follow: false,
    rotation: [120, 0, 25],
    direction: [0, 0, 0],
    darkness: 0.75,
    bias: 0.0005,
    filter: 0,
  },
  controller: '',
  dpr: 0,
  fps: 30,
  fxaa: 1,
  texture_level: 1,
  hudscale: 1,
  orientation: 0,
  css: '',
  physics_debug_level: 0,
  fov_size: [500, 500, 500],
  render_method: 0,
  fov_enabled: false,
  lod_enabled: false,
  zip_size: [1000, 1000, 1000],
  zip_enabled: false,
  dprFixed: false,
  resolution: 1080,
  bloom_bias: 0.045,
  bloom_radius: 0.005,
  exposure: 1,
  near: 0.01,
  far: 200,
  fov: 45,
};
