export const NODE_TYPES = {
  hud: 'hud',
  hudLink: 'hud-link',
  HTMLHudElement: 'HTMLElement',
  HTMLHudLink: 'HTMLElement-link',
  image: 'image',
  imageLink: 'image-link',
  light: 'light',
  lightLink: 'light-link',
  object: 'object',
  objectLink: 'object-link',
  objectHud: 'object-hud',
  objectHudLink: 'object-hud-link',
  objectGroup: 'object-group',
  objectGroupLink: 'object-group-link',
  video: 'video',
  videoLink: 'video-link',
  camera: 'camera',
  configuration: 'configuration',
  folder: 'folder',
  javascript: 'javascript',
  stylesheet: 'stylesheet',
  file: 'file',
  ZIPElement: 'ZIPElement',
  ZIPAsset: 'ZIPAsset',

  RigidBody: 'RigidBody',
  KinematicCharacterController: 'KinematicCharacterController',
  RaycastVehicle: 'RaycastVehicle',

} as const;
