name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: fregante/setup-git-user@v1

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile

      - name: Release new version
        run: yarn release

      - name: Build package
        run: yarn build

      - uses: actions/upload-artifact@v2
        with:
          name: bundled-package
          path: dist

      - name: Push release
        run: git push --follow-tags

      - name: Update develop branch
        run: |
          git checkout develop
          git rebase main
          git push

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bundled-package

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/

      - name: Deploy package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
